# Generated by Django 4.1.7 on 2023-04-05 03:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Name', models.CharField(max_length=300)),
                ('Book_Code', models.CharField(max_length=300)),
                ('Author_Name', models.CharField(max_length=300)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Status', models.CharField(max_length=300)),
                ('Created_Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('userid', models.CharField(max_length=200)),
                ('password', models.IntegerField()),
                ('mobilenumber', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('Delivery_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Status', models.CharField(max_length=200)),
                ('Created_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Book_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookStore.bookdetail')),
            ],
        ),
    ]
