# Generated by Django 4.1.7 on 2023-04-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetail',
            name='Created_By',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='Created_By',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='Total_Count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
