# Generated by Django 4.1.7 on 2023-04-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0002_bookdetail_created_by_orderdetail_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='Created_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='Delivery_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
